### ISSUE TITLE
Split app from the firmware

### ISSUE THREAD

**Issue by Fokko** [ps2/rileylink#24]
Hi Guys,

I am getting a lot of messages from the repository. Would it be possible to split the GlucoseLink app from the firmware of the RileyLink. Would be great and it will be much clearer for me when the RileyLink needs to be updated.

Cheers,
Fokko

**Comment by ps2** [comment]
Yeah, I think this makes sense. I plan on following this method to do so: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ .

**Comment by ps2** [comment]
Moved iOS app to https://github.com/ps2/rileylink_ios
