### ISSUE TITLE
semver for cc1110 firmware

### ISSUE THREAD

**Issue by ps2** [ps2/rileylink#29]
This should also be made visible as a bluetooth attribute

**Comment by ehwest** [comment]
Can you please document somewhere exactly how the RF modem used for the Nightscout project relates to the cc1110 firmware properties?  How did you select the requisite header file values?

**Comment by ps2** [comment]
Not sure what you're asking here.  This ticket is about letting users know which version of firmware they currently have installed on their device.

The gitter channel (https://gitter.im/ps2/rileylink) is a good place to ask general questions about this project.

**Comment by ps2** [comment]
We have firmware version reporting from subg_rfspy now.
