### ISSUE TITLE
R9 - where is it?

### ISSUE THREAD

**Issue by javaboyjunior** [ps2/rileylink#58]
I can find R9 on the PCB, silk screen or in Eagle but it is on the parts list. What am I missing? Thanks!

**Comment by breakery** [comment]
R9 is next to the ANT (antenna).
![Bildschirmfoto 2019-05-08 um 13 42 25](https://user-images.githubusercontent.com/15985187/57373069-b4460980-7197-11e9-8e71-6b7ce28f047f.png)

**Comment by javaboyjunior** [comment]
Thanks!
