### ISSUE TITLE
Firmware question

### ISSUE THREAD

**Issue by javaboyjunior** [ps2/rileylink#60]
Thank you for answering my questions, this should be it. For background, I have built one RileyLink and it didn't work - the BLE and C1110 were not talking to each other. 

Am on my second today and want to make sure I don't miss any steps. This is what I followed up load the firmware last time:

https://getrileylink.org/wp-content/uploads/2018/08/RileyLink-Firmware-Update-August-2018.pdf

Is this everything?

Thanks again.

**Comment by breakery** [comment]
Can you provide any errors that you encountered while flashing the firmwares?
